### ISSUE TITLE
Fix color of textfields 

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/enternot-app#26]
<item name="android:textColor">someblackcolor</item>

Add this to theme.

**Comment by Shynixn** [comment]
Added potential fix to master but cannot recreate the issue. Tested on 2 smartphones with Android 5, 7 and Tablet Android 6.

**Comment by korti11** [comment]
Is fixed. Tested on Android 8 Device. Maybe testing needed on my development branche for the action menu in landscape mode where the text of the menu items is also white on a white menu background.
![screenshot_enternot_20180608-094227](https://user-images.githubusercontent.com/5838137/41145638-16d855f6-6b01-11e8-8c89-39b2ccbbb2bf.png)

**Comment by Shynixn** [comment]
Should be fixed in master.

**Comment by korti11** [comment]
Dialog button text need a color change to black.

**Comment by Shynixn** [comment]
fixed.
