### ISSUE TITLE
Add firebase for analyzing crashes

### ISSUE THREAD

**Issue by Shynixn** [Shynixn/enternot-app#37]
https://www.hockeyapp.net/#s

**Comment by korti11** [comment]
Firebase has also tools for analyzing crashes. Why should we use a extra tool instead of one that we already use parts of ? 🤔

**Comment by Shynixn** [comment]
Didn't know about that yet, can you integrate it easily?

**Comment by korti11** [comment]
https://firebase.google.com/docs/reference/android/com/google/firebase/crash/FirebaseCrash

should be not that hard 🤔 it's one dependency and then you have these methods available. the reports are then available in the firebase project

**Comment by Shynixn** [comment]
Added.
